# Generated by Django 3.0.2 on 2020-04-07 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='contract_number',
        ),
    ]
