# Generated by Django 3.0.6 on 2020-05-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_contract_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='jsa',
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscribe_to_emails',
            field=models.BooleanField(default=True),
        ),
    ]
