# start from an official image
FROM nginx:latest
ARG UFTS_UID
ARG UFTS_GID

COPY config/nginx/group /etc/group 
RUN groupmod -g "${UFTS_GID}" nginx && usermod -u "${UFTS_UID}" nginx
COPY config/nginx/nginx.conf /etc/nginx/nginx.conf
RUN chown -R nginx:nginx /var/cache/nginx && \
    chown -R nginx:nginx /var/log/nginx && \
    chown -R nginx:nginx /etc/nginx/conf.d
RUN touch /var/run/nginx.pid && \
    chown -R nginx:nginx /var/run/nginx.pid
EXPOSE 8080
USER nginx:nginx
