# start from an official image
FROM python:3.6

# arbitrary location choice: you can change the directory
RUN mkdir -p /opt/services/ufts/src
WORKDIR /opt/services/ufts/src
RUN groupadd -g 1000 -r celery && useradd -u 1000 --no-log-init -r -g celery celery
RUN mkdir -p /var/run/celery/
RUN chown celery:celery /var/run/celery
# install our dependencies
# we use --system flag because we don't need an extra virtualenv
COPY Pipfile Pipfile.lock /opt/services/ufts/src/
RUN pip install pipenv && pipenv install --system
USER celery:celery
