# Generated by Django 2.1.1 on 2019-08-30 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_type', models.CharField(default='', max_length=100)),
                ('prod_family', models.CharField(default='', max_length=100)),
                ('prod_model', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='support/software')),
                ('version', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('description', models.CharField(max_length=200)),
                ('md5sum', models.CharField(blank=True, editable=False, help_text='128bit, 32 Characters', max_length=32)),
                ('sha256sum', models.CharField(blank=True, editable=False, help_text='256bit, 64 Characters', max_length=64)),
                ('uploaded_date', models.DateField(auto_now_add=True)),
                ('verified_date', models.DateField(auto_now=True)),
                ('products', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='uploads.Products')),
            ],
        ),
    ]
