# Generated by Django 2.1.1 on 2020-01-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20190830_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='md5sum',
            field=models.CharField(blank=True, help_text='128bit, 32 Characters', max_length=32),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='sha256sum',
            field=models.CharField(blank=True, help_text='256bit, 64 Characters', max_length=64),
        ),
    ]
