# Generated by Django 3.0.2 on 2020-04-03 20:00

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_uploadfile_release_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='release_notes',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/software/release_notes/', location='/opt/services/ufts/software/release_notes/'), upload_to=''),
        ),
    ]
